version: '3'

services:
  web:
    image: albreis/codeigniter
    build: .
    ports:
      - "8009:80"
    volumes:
      - ./app:/var/www
    environment:
      - CI_ENV=development
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=codeigniter
      - MYSQL_USER=codeigniter
      - MYSQL_PASSWORD=codeigniter
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: